export const AYAT_JAMINAN = [
  {
    order: 1,
    label: "Jaminan Keselamatan",
    verse: "1 Yohanes 5:11-12",
    text: "Inilah kesaksian itu: Allah telah mengaruniakan hidup yang kekal kepada kita dan hidup itu ada di dalam Anak-Nya. Siapa yang memiliki Anak, ia memiliki hidup; siapa yang tidak memiliki Anak, ia tidak memiliki hidup.",
  },
  {
    order: 2,
    label: "Jaminan Jawaban Doa",
    verse: "Yohanes 16:24",
    text: "Sampai sekarang kamu belum meminta sesuatu pun dalam nama-Ku. Mintalah maka kamu akan menerima, supaya penuhlah sukacitamu.",
  },
  {
    order: 3,
    label: "Jaminan Kemenangan Atas Pencobaan",
    verse: "1 Korintus 10:13",
    text: "Pencobaan-pencobaan yang kamu alami ialah pencobaan biasa yang tidak melebihi kekuatan manusia. Allah itu setia dan tidak akan membiarkan kamu dicobai melampaui kekuatanmu. Pada waktu kamu dicobai Ia akan memberikan kepadamu jalan keluar, sehingga kamu dapat menanggungnya.",
  },
  {
    order: 4,
    label: "Jaminan Pengampunan Dosa",
    verse: "1 Yohanes 1:9",
    text: "Jika kita mengaku dosa kita, Ia setia dan adil, sehingga Ia akan mengampuni segala dosa kita dan menyucikan kita dari segala kejahatan.",
  },
  {
    order: 5,
    label: "Jaminan Bimbingan Tuhan",
    verse: "Amsal 3:5-6",
    text: "Percayalah kepada Tuhan dengan segenap hatimu, dan janganlah bersandar pada pengertianmu sendiri. Akuilah Dia dalam seluruh hidupmu, maka Ia akan meluruskan jalanmu.",
  },
];

export interface Verse {
  order: number;
  label: string;
  verse: string;
  text: string;
}

export const AYAT_HAFALAN = [
  {
    label: "A",
    title: "Kehidupan Baru",
    verses: [
      {
        order: 1,
        label: "Kristus Sebagai Pusat",
        verse: "2 Korintus 5:17",
        text: "Jadi, siapa yang ada di dalam Kristus, ia adalah ciptaan baru: Yang lama sudah berlalu, sesungguhnya yang baru sudah datang.",
      },
      {
        order: 2,
        label: "Kristus Sebagai Pusat",
        verse: "Galatia 2:19b-20",
        text: "Aku telah disalibkan dengan Kristus. Namun, aku hidup, tetapi bukan lagi aku sendiri yang hidup, melainkan Kristus yang hidup di dalam aku. Hidup yang sekarang aku hidupi secara jasmani adalah hidup oleh iman dalam Anak Allah yang telah mengasihi aku dan menyerahkan diri-Nya untuk aku.",
      },
      {
        order: 3,
        label: "Ketataatan Kepada Kristus",
        verse: "Roma 12:1",
        text: "Karena itu, Saudara-saudara, oleh kemurahan Allah aku menasihatkan kamu, supaya kamu mempersembahkan tubuhmu sebagai persembahan yang hidup, yang kudus, dan yang berkenan kepada Allah: Itulah ibadahmu yang sejati.",
      },
      {
        order: 4,
        label: "Ketataatan Kepada Kristus",
        verse: "Yohanes 14:21",
        text: "Siapa yang memegang perintah-perintah-Ku dan melakukannya, dialah yang mengasihi Aku. Siapa yang mengasihi Aku, ia akan dikasihi oleh Bapa-Ku dan Aku pun akan mengasihi dia dan akan menyatakan diri-Ku kepadanya.",
      },
      {
        order: 5,
        label: "Firman Tuhan",
        verse: "2 Timotius 3:16",
        text: "Seluruh Kitab Suci diilhamkan Allah dan bermanfaat untuk mengajar, untuk menyatakan kesalahan, untuk memperbaiki kelakuan, dan untuk mendidik orang dalam kebenaran.",
      },
      {
        order: 6,
        label: "Firman Tuhan",
        verse: "Kolose 3:16",
        text: "Hendaklah perkataan Kristus tinggal dengan limpahnya di antara kamu, sehingga kamu dengan segala hikmat mengajar dan menegur seorang akan yang lain dan sambil menyanyikan mazmur, puji-pujian dan nyanyian rohani, kamu mengucap syukur kepada Allah di dalam hatimu.",
      },
      {
        order: 7,
        label: "Doa",
        verse: "Yohanes 15:7",
        text: "Jikalau kamu tinggal di dalam Aku dan firman-Ku tinggal di dalam kamu, mintalah apa yang kamu kehendaki, maka akan diberikan kepadamu.",
      },
      {
        order: 8,
        label: "Doa",
        verse: "Filipi 4:6-7",
        text: "Janganlah khawatir tentang apapun juga, tetapi nyatakanlah dalam segala hal keinginanmu kepada Allah dalam doa dan permohonan dengan ucapan syukur. Damai sejahtera Allah, yang melampaui segala akal, akan memelihara hati dan pikiranmu dalam Kristus Yesus.",
      },
      {
        order: 9,
        label: "Persekutuan",
        verse: "Matius 18:20",
        text: "Sebab, di mana dua atau tiga orang berkumpul dalam nama-Ku, di situ Aku ada di tengah-tengah mereka.",
      },
      {
        order: 10,
        label: "Persekutuan",
        verse: "Ibrani 10:24-25",
        text: "Marilah kita saling memperhatikan supaya kita saling mendorong dalam kasih dan dalam perbuatan baik. Janganlah kita menjauhkan diri dari pertemuan-pertemuan ibadah kita, seperti yang dibiasakan oleh beberapa orang, tetapi marilah kita saling menasihati, terlebih lagi sementara kamu melihat hari Tuhan semakin mendekat",
      },
      {
        order: 11,
        label: "Bersaksi",
        verse: "Kisah Para Rasul 1:8",
        text: "Tetapi, kamu akan menerima kuasa bilamana Roh Kudus turun ke atas kamu, dan kamu akan menjadi saksi-saksi-Ku di Yerusalem, di seluruh Yudea dan Samaria dan sampai ke ujung bumi.",
      },
      {
        order: 12,
        label: "Bersaksi",
        verse: "1 Yohanes 1:3",
        text: "Apa yang telah kami lihat dan kami dengar itu, kami beritakan kepada kamu juga, supaya kamu pun mempunyai persekutuan dengan kami. Persekutuan kami adalah persekutuan dengan Bapa dan dengan Anak-Nya, Yesus Kristus.",
      },
    ],
  },
  {
    label: "B",
    title: "Injil",
    verses: [
      {
        order: 1,
        label: "Semua Berdosa",
        verse: "Roma 3:23",
        text: "Karena semua orang telah berbuat dosa dan kehilangan kemuliaan Allah.",
      },
      {
        order: 2,
        label: "Semua Berdosa",
        verse: "Yohanes 3:19",
        text: "Inilah hukuman itu: Terang telah datang ke dalam dunia, tetapi manusia lebih menyukai kegelapan daripada terang, sebab perbuatan-perbuatan mereka jahat.",
      },
      {
        order: 3,
        label: "Hukuman Dosa",
        verse: "Roma 6:23",
        text: "Sebab, upah dosa ialah maut, tetapi karunia Allah ialah hidup yang kekal dalam Kristus Yesus, Tuhan kita.",
      },
      {
        order: 4,
        label: "Hukuman Dosa",
        verse: "Roma 5:12",
        text: "Sebab itu, sama seperti dosa telah masuk ke dalam dunia oleh satu orang, dan melalui dosa itu juga maut, demikianlah maut itu telah menjalar kepada semua orang, karena semua orang telah berbuat dosa.",
      },
      {
        order: 5,
        label: "Hukuman Dibayar Kristus",
        verse: "Roma 5:8",
        text: "Namun, Allah menunjukkan kasih-Nya kepada kita dalam hal ini: Ketika kita masih berdosa, Kristus telah mati untuk kita.",
      },
      {
        order: 6,
        label: "Hukuman Dibayar Kristus",
        verse: "1 Petrus 3:18",
        text: "Sebab, juga Kristus telah menderita sekali untuk dosa-dosa kita, Ia yang benar untuk orang-orang yang tidak benar, supaya Ia membawa kamu kepada Allah. Ia, yang telah dibunuh dalam keadaan-Nya sebagai manusia, tetapi telah dihidupkan menurut Roh.",
      },
      {
        order: 7,
        label: "Keselamatan Anugerah Allah",
        verse: "Efesus 2:8-9",
        text: "Sebab karena anugerah kamu diselamatkan oleh iman; itu bukan hasil usahamu, tetapi pemberian Allah, itu bukan hasil pekerjaanmu, supaya tidak ada orang yang memegahkan diri.",
      },
      {
        order: 8,
        label: "Keselamatan Anugerah Allah",
        verse: "Roma 3:24",
        text: "Dan oleh anugerah-Nya telah dibenarkan dengan cuma-cuma melalui penebusan dalam Kristus Yesus.",
      },
      {
        order: 9,
        label: "Harus Menerima Kristus",
        verse: "Yohanes 1:12",
        text: "Namun, semua orang yang menerima-Nya diberi-Nya hak supaya menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya.",
      },
      {
        order: 10,
        label: "Harus Menerima Kristus",
        verse: "Wahyu 3:20",
        text: "Lihat, Aku berdiri di depan pintu dan mengetuk. Jikalau ada orang yang mendengar suara-Ku dan membukakan pintu, Aku akan masuk menemui dia dan makan bersama dia dan ia bersama Aku.",
      },
      {
        order: 11,
        label: "Jaminan Keselamatan",
        verse: "Yohanes 5:24",
        text: "Sesungguhnya Aku berkata kepadamu: Siapa saja yang mendengar perkataan-Ku dan percaya kepada Dia yang mengutus Aku, ia mempunyai hidup yang kekal dan tidak turut dihukum, sebab ia sudah pindah dari dalam maut ke dalam hidup.",
      },
      {
        order: 12,
        label: "Jaminan Keselamatan",
        verse: "1 Yohanes 5:11-12",
        text: "Inilah kesaksian itu: Allah telah mengaruniakan hidup yang kekal kepada kita dan hidup itu ada di dalam Anak-Nya. Siapa yang memiliki Anak, ia memiliki hidup; siapa yang tidak memiliki Anak, ia tidak memiliki hidup.",
      },
    ],
  },
  {
    label: "C",
    title: "Perlengkapan Dari Tuhan",
    verses: [
      {
        order: 1,
        label: "Roh Kudus",
        verse: "1 Korintus 2:12",
        text: "Kita tidak menerima roh dunia, tetapi roh yang berasal dari Allah, supaya kita tahu apa yang dikaruniakan Allah kepada kita.",
      },
      {
        order: 2,
        label: "Roh Kudus",
        verse: "Yohanes 14:26",
        text: "Namun, Penolong, yaitu Roh Kudus, yang akan diutus oleh Bapa dalam nama-Ku, Dialah yang akan mengajarkan segala sesuatu kepadamu dan mengingatkan kamu akan semua yang telah Kukatakan kepadamu.",
      },
      {
        order: 3,
        label: "Kekuatan",
        verse: "Filipi 4:13",
        text: "Segala hal dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.",
      },
      {
        order: 4,
        label: "Kekuatan",
        verse: "Yesaya 41:10",
        text: "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu; Aku akan meneguhkan, bahkan akan menolong engkau; Aku akan memegang engkau dengan tangan kanan-Ku yang membawa kemenangan.",
      },
      {
        order: 5,
        label: "Kesetiaan",
        verse: "Bilangan 23:19",
        text: "Allah bukanlah manusia, sehingga Ia berdusta dan bukan anak manusia, sehingga Ia menyesal. Mungkinlah Ia berfirman dan tidak melakukannya, atau berbicara dan tidak menepatinya?",
      },
      {
        order: 6,
        label: "Kesetiaan",
        verse: "Ratapan 3:22-23",
        text: "Tak berkesudahan kasih setia Tuhan, tak habis-habisnya rahmat-Nya, selalu baru tiap pagi, besar kesetiaan-Mu!",
      },
      {
        order: 7,
        label: "Sejahtera",
        verse: "1 Petrus 5:7",
        text: "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia memelihara kamu.",
      },
      {
        order: 8,
        label: "Sejahtera",
        verse: "Yohanes 14:27",
        text: "Damai sejahtera Kutinggalkan bagimu. Damai sejahtera-Ku Kuberikan kepadamu, dan Aku memberi kepadamu tidak seperti dunia memberi. Janganlah gelisah dan gentar hatimu.",
      },
      {
        order: 9,
        label: "Pemeliharaan",
        verse: "Roma 8:32",
        text: "Ia, yang tidak menyayangkan Anak-Nya sendiri, tetapi yang menyerahkan-Nya bagi kita semua, bagaimana mungkin Ia tidak mengaruniakan segala sesuatu kepada kita bersama-sama dengan Dia?",
      },
      {
        order: 10,
        label: "Pemeliharaan",
        verse: "Filipi 4:19",
        text: "Allahku akan memenuhi segala keperluanmu menurut kekayaan dan kemuliaan-Nya dalam Kristus Yesus.",
      },
      {
        order: 11,
        label: "Kemenangan",
        verse: "1 Korintus 10:13",
        text: "Pencobaan-pencobaan yang kamu alami ialah pencobaan biasa yang tidak melebihi kekuatan manusia. Allah itu setia dan tidak akan membiarkan kamu dicobai melampaui kekuatanmu. Pada waktu kamu dicobai Ia akan memberikan kepadamu jalan keluar, sehingga kamu dapat menanggungnya.",
      },
      {
        order: 12,
        label: "Kemenangan",
        verse: "1 Yohanes 5:4-5",
        text: "Sebab semua yang lahir dari Allah, mengalahkan dunia. Inilah kemenangan yang mengalahkan dunia: Iman kita. Siapakah yang mengalahkan dunia, selain dia yang percaya bahwa Yesuslah Anak Allah?",
      },
    ],
  },
  {
    label: "D",
    title: "Tantangan Pemuridan",
    verses: [
      {
        order: 1,
        label: "Utamakan Kristus",
        verse: "Matius 6:33",
        text: "Tetapi carilah dahulu Kerajaan Allah dan kebenaran-Nya, dan semuanya itu akan ditambahkan kepadamu.",
      },
      {
        order: 2,
        label: "Utamakan Kristus",
        verse: "Lukas 9:23",
        text: "Yesus berkata kepada mereka semua: Jika seseorang mau mengikuti Aku, ia harus menyangkal dirinya, memikul salibnya setiap hari dan mengikut Aku.",
      },
      {
        order: 3,
        label: "Bercerai Dari Dunia",
        verse: "1 Yohanes 2:15-16",
        text: "Janganlah mengasihi dunia dan apa yang ada di dalamnya. Jikalau orang mengasihi dunia, kasih kepada Bapa tidak ada di dalam orang itu. Sebab, semua yang ada di dalam dunia, yaitu keinginan daging, keinginan mata, dan keangkuhan hidup, tidak berasal dari Bapa, melainkan dari dunia.",
      },
      {
        order: 4,
        label: "Bercerai Dari Dunia",
        verse: "Roma 12:2",
        text: "Janganlah menjadi serupa dengan dunia ini, tetapi berubahlah oleh pembaharuan budimu, sehingga kamu dapat membedakan manakah kehendak Allah: apa yang baik, yang berkenan kepada-Nya dan sempurna.",
      },
      {
        order: 5,
        label: "Berdirilah Tetap",
        verse: "1 Korintus 15:58",
        text: "Karena itu, Saudara-saudaraku yang terkasih, berdirilah teguh, jangan goyah, dan giatlah selalu dalam pekerjaan Tuhan! Sebab, kamu tahu bahwa dalam persekutuan dengan Tuhan jerih payahmu tidak sia-sia.",
      },
      {
        order: 6,
        label: "Berdirilah Tetap",
        verse: "Ibrani 12:3",
        text: "Ingatlah selalu Dia yang tekun menanggung bantahan yang sehebat itu terhadap diri-Nya dari pihak orang-orang berdosa, supaya jangan kamu menjadi lemah dan putus asa.",
      },
      {
        order: 7,
        label: "Layani Orang Lain",
        verse: "Markus 10:45",
        text: "Karena Anak Manusia juga datang bukan untuk dilayani, melainkan untuk melayani dan untuk memberikan nyawa-Nya menjadi tebusan bagi banyak orang.",
      },
      {
        order: 8,
        label: "Layani Orang Lain",
        verse: "2 Korintus 4:5",
        text: "Sebab, bukan diri kami yang kami beritakan, tetapi Yesus Kristus sebagai Tuhan, dan diri kami sebagai hambamu karena kehendak Yesus.",
      },
      {
        order: 9,
        label: "Beri Dengan Sukacita",
        verse: "Amsal 3:9-10",
        text: "Muliakanlah Tuhan dengan hartamu dan dengan buah sulung dari hasil tanahmu, maka lumbung-lumbungmu akan terisi penuh sampai melimpah-limpah, dan bejana pemerasanmu akan meluap dengan air buah anggurnya.",
      },
      {
        order: 10,
        label: "Beri Dengan Sukacita",
        verse: "2 Korintus 9:6-7",
        text: "Perhatikanlah ini: Orang yang menabur sedikit, akan menuai sedikit juga, dan orang yang menabur banyak, akan menuai banyak juga. Hendaklah masing-masing memberi menurut kerelaan hatinya, jangan dengan sedih hati atau karena paksaan, sebab Allah mengasihi orang yang memberi dengan sukacita.",
      },
      {
        order: 11,
        label: "Amanat Agung",
        verse: "Markus 16:15",
        text: `Lalu Ia berkata kepada mereka, "Pergilah ke seluruh dunia, beritakanlah Injil kepada segala makhluk."`,
      },
      {
        order: 12,
        label: "Amanat Agung",
        verse: "Matius 28:19-20",
        text: "Karena itu, pergilah, jadikanlah semua bangsa murid-Ku, dan baptislah mereka dalam nama Bapa dan Anak dan Roh Kudus, dan ajarlah mereka melakukan segala sesuatu yang telah Kuperintahkan kepadamu. Ketahuilah, Aku menyertai kamu senantiasa sampai akhir zaman.",
      },
    ],
  },
  {
    label: "E",
    title: "Sifat-Sifat Murid Kristus",
    verses: [
      {
        order: 1,
        label: "Kasih",
        verse: "Yohanes 13:34-35",
        text: "Aku memberikan perintah baru kepada kamu, yaitu supaya kamu saling mengasihi. Sama seperti Aku telah mengasihi kamu demikian pula kamu harus saling mengasihi. Dengan demikian semua orang akan tahu bahwa kamu adalah murid-murid-Ku, jikalau kamu saling mengasihi.",
      },
      {
        order: 2,
        label: "Kasih",
        verse: "1 Yohanes 3:18",
        text: "Anak-anakku, marilah kita mengasihi bukan dengan perkataan atau dengan lidah, tetapi dengan perbuatan dan dalam kebenaran.",
      },
      {
        order: 3,
        label: "Rendah Hati",
        verse: "Matius 20:26-27",
        text: "Tidaklah demikian di antara kamu. Siapa saja yang ingin menjadi yang besar di antara kamu, hendaklah ia menjadi pelayanmu. Siapa saja yang ingin menjadi yang pertama di antara kamu, hendaklah ia menjadi hambamu.",
      },
      {
        order: 4,
        label: "Rendah Hati",
        verse: "1 Petrus 5:5-6",
        text: `Demikian juga, orang-orang muda, tunduklah kepada orang-orang yang tua. Kamu semua, rendahkanlah dirimu seorang terhadap yang lain, sebab, "Allah menentang orang yang congkak, tetapi memberi anugerah kepada orang yang rendah hati." Karena itu, rendahkanlah dirimu di bawah tangan Tuhan yang kuat, supaya kamu ditinggikan-Nya pada waktunya.`,
      },
      {
        order: 5,
        label: "Kemurnian",
        verse: "Efesus 5:3",
        text: "Tetapi, percabulan dan rupa-rupa kecemaran atau keserakahan disebut saja pun jangan di antara kamu, sebagaimana sepatutnya bagi orang-orang kudus.",
      },
      {
        order: 6,
        label: "Kemurnian",
        verse: "1 Petrus 2:11",
        text: "Saudara-saudaraku yang terkasih, aku menasihati kamu, supaya sebagai pendatang dan perantau, kamu menjauhkan diri dari keinginan-keinginan daging yang berjuang melawan jiwa.",
      },
      {
        order: 7,
        label: "Kejujuran",
        verse: "Imamat 19:11",
        text: "Janganlah kamu mencuri, janganlah kamu berbohong, dan janganlah kamu menipu satu sama lain.",
      },
      {
        order: 8,
        label: "Kejujuran",
        verse: "Kisah Para Rasul 24:16",
        text: "Sebab itu, aku senantiasa berusaha untuk hidup dengan hati nurani yang murni di hadapan Allah dan manusia.",
      },
      {
        order: 9,
        label: "Iman",
        verse: "Ibrani 11:6",
        text: "Namun, tanpa iman tidak mungkin orang berkenan kepada Allah. Sebab, siapa yang datang kepada Allah, ia harus percaya bahwa Allah ada, dan bahwa Allah memberi upah kepada orang yang sungguh-sungguh mencari Dia.",
      },
      {
        order: 10,
        label: "Iman",
        verse: "Roma 4:20-21",
        text: "Namun, terhadap janji Allah ia tidak bimbang karena ketidakpercayaan, malah ia diperkuat dalam imannya dan ia memuliakan Allah, serta berkeyakinan penuh bahwa Allah berkuasa untuk melaksanakan apa yang telah Ia janjikan.",
      },
      {
        order: 11,
        label: "Kebajikan",
        verse: "Galatia 6:9-10",
        text: "Janganlah kita jemu-jemu berbuat baik, karena apabila sudah datang waktunya, kita akan menuai, jika kita tidak menyerah. Karena itu, selama masih ada kesempatan bagi kita, marilah kita berbuat baik kepada semua orang, tetapi terutama kepada saudara-saudara seiman kita.",
      },
      {
        order: 12,
        label: "Kebajikan",
        verse: "Efesus 2:10",
        text: "Karena kita ini buatan Allah, diciptakan dalam Kristus Yesus untuk melakukan pekerjaan baik, yang dipersiapkan Allah sebelumnya. Ia mau, supaya kita hidup di dalamnya.",
      },
    ],
  },
  {
    label: "F",
    title: "Langkah-langkah Dalam Membagikan Imanmu",
    verses: [
      {
        order: 1,
        label: "Doa",
        verse: "Roma 10:1",
        text: "Saudara-saudara, kerinduan hatiku dan doaku kepada Allah ialah supaya mereka diselamatkan.",
      },
      {
        order: 2,
        label: "Doa",
        verse: "Kolose 4:12",
        text: "Salam dari Epafras kepada kamu; ia seorang dari antara kamu, hamba Kristus Yesus, yang selalu bergumul dalam doanya untuk kamu, supaya kamu berdiri teguh, sebagai orang-orang yang dewasa dan berkeyakinan penuh dalam segala hal yang dikehendaki Allah.",
      },
      {
        order: 3,
        label: "Bergantung pada Roh Kudus",
        verse: "1 Korintus 2:4-5",
        text: "Baik perkataanku maupun pemberitaanku tidak kusampaikan dengan kata-kata hikmat yang meyakinkan, tetapi dengan bukti bahwa Roh berkuasa, 'Baik perkataanku maupun pemberitaanku tidak kusampaikan dengan kata-kata hikmat yang meyakinkan, tetapi dengan bukti bahwa Roh berkuasa, supaya iman kamu jangan bergantung pada hikmat manusia, tetapi pada kekuatan Allah.",
      },
      {
        order: 4,
        label: "Bergantung pada Roh Kudus",
        verse: "Zakharia 4:6",
        text: `Ia menjawab lagi, katanya kepadaku, "Inilah firman Tuhan kepada Zerubabel, bunyinya: Bukan dengan keperkasaan dan bukan dengan kekuatan, melainkan dengan roh-Ku, firman Tuhan semesta alam."`,
      },
      {
        order: 5,
        label: "Sesuaikan dengan Orang Lain",
        verse: "1 Korintus 9:22-23",
        text: "Bagi orang-orang yang lemah aku menjadi seperti orang yang lemah, supaya aku dapat memenangkan mereka yang lemah. Bagi semua orang aku telah menjadi segala-galanya, supaya aku sedapat mungkin menyelamatkan beberapa orang dari antara mereka. Semuanya ini aku lakukan karena Injil, supaya aku mendapat bagian di dalamnya.",
      },
      {
        order: 6,
        label: "Sesuaikan dengan Orang Lain",
        verse: "Roma 15:1",
        text: "Kita, yang kuat, wajib menanggung kelemahan orang yang tidak kuat dan jangan kita mencari kesenangan kita sendiri.",
      },
      {
        order: 7,
        label: "Timbulkan Perhatian dengan Hidup",
        verse: "1 Petrus 3:1",
        text: "Demikian juga kamu, hai istri-istri, tunduklah kepada suamimu, supaya jika ada di antara mereka yang tidak taat kepada Firman, mereka juga tanpa perkataan dimenangkan oleh kelakuan istrinya.",
      },
      {
        order: 8,
        label: "Timbulkan Perhatian dengan Hidup",
        verse: "Amsal 11:30",
        text: "Buah orang benar adalah pohon kehidupan, dan siapa bijak, mengambil hati orang.",
      },
      {
        order: 9,
        label: "Rangsangkan Perhatian dengan Kesaksian",
        verse: "Yohanes 9:25",
        text: `Jawabnya, "Apakah orang itu orang berdosa, aku tidak tahu; tetapi satu hal aku tahu, yaitu bahwa aku tadinya buta, dan sekarang dapat melihat."`,
      },
      {
        order: 10,
        label: "Rangsangkan Perhatian dengan Kesaksian",
        verse: "Filipi 3:7-8",
        text: "Tetapi apa yang dahulu merupakan keuntungan bagiku, sekarang kuanggap rugi karena Kristus. Tetapi apa yang dahulu merupakan keuntungan bagiku, sekarang kuanggap rugi karena Kristus. Malahan segala sesuatu kuanggap rugi, karena pengenalan akan Kristus Yesus, Tuhanku, lebih mulia daripada semuanya. Karena Dialah aku telah melepaskan semuanya itu dan menganggapnya sampah, supaya aku memperoleh Kristus.",
      },
      {
        order: 11,
        label: "Harapkan Suatu Sambutan",
        verse: "2 Korintus 5:20",
        text: "Jadi, kami ini utusan-utusan Kristus, seakan-akan Allah menasihati kamu dengan perantaraan kami; dalam nama Kristus kami meminta kepadamu: Berilah dirimu didamaikan dengan Allah.",
      },
      {
        order: 12,
        label: "Harapkan Suatu Sambutan",
        verse: "Yehezkiel 33:11",
        text: "Katakanlah kepada mereka: Demi Aku yang hidup, demikianlah firman Tuhan Allah, Aku tidak berkenan pada kematian orang fasik, melainkan Aku berkenan pada pertobatan orang fasik itu dari tingkah lakunya supaya ia hidup. Bertobatlah, bertobatlah dari hidupmu yang jahat itu! Mengapa kamu harus mati, hai kaum Israel?",
      },
    ],
  },
  {
    label: "G",
    title: "Menyampaikan Injil",
    verses: [
      {
        order: 1,
        label: "Semua berdosa",
        verse: "Pengkhotbah 7:20",
        text: "Sesungguhnya, di bumi tidak ada orang saleh yang berbuat baik tanpa pernah berbuat dosa!",
      },
      {
        order: 2,
        label: "Semua berdosa",
        verse: "Mazmur 53:4",
        text: "Tetapi, semua telah menyimpang, sekaliannya telah bejat; tidak ada yang berbuat baik, seorang pun tidak.",
      },
      {
        order: 3,
        label: "Hukuman Bagi Dosa",
        verse: "Roma 5:12",
        text: "Sebab itu, sama seperti dosa telah masuk ke dalam dunia melalui satu orang, dan melalui dosa itu juga maut, demikianlah maut itu telah menjalar kepada semua orang, karena semua orang telah berbuat dosa.",
      },
      {
        order: 4,
        label: "Hukuman Bagi Dosa",
        verse: "Yehezkiel 18:4",
        text: "Sungguh, semua nyawa itu milik-Ku! Baik nyawa ayah maupun nyawa anak itu milik-Ku! Siapa yang berbuat dosa, dialah yang harus mati.",
      },
      {
        order: 5,
        label: "Kristus Membayar Hukuman",
        verse: "1 Petrus 2:24",
        text: "Ia sendiri telah memikul dosa kita di dalam tubuh-Nya di kayu salib, supaya kita, yang telah mati terhadap dosa, hidup untuk kebenaran. Oleh bilur-bilur-Nya kamu telah sembuh.",
      },
      {
        order: 6,
        label: "Kristus Membayar Hukuman",
        verse: "1 Yohanes 3:5",
        text: "Dan kamu tahu bahwa Ia telah menyatakan diri-Nya, supaya Ia menghapus segala dosa, dan di dalam Dia tidak ada dosa.",
      },
      {
        order: 7,
        label: "Keselamatan Bukan Karena Perbuatan",
        verse: "Roma 4:5",
        text: "Tetapi kepada orang yang tidak bekerja, namun percaya kepada Dia yang membenarkan orang fasik, imannya diperhitungkan sebagai kebenaran.",
      },
      {
        order: 8,
        label: "Keselamatan Bukan Karena Perbuatan",
        verse: "Galatia 2:16",
        text: `Kita tahu bahwa tidak seorang pun yang dibenarkan karena melakukan hukum Taurat, tetapi hanya melalui iman dalam Kristus Yesus. Sebab itu, kami pun telah percaya kepada Kristus Yesus, supaya kami dibenarkan karena iman dalam Kristus dan bukan karena melakukan hukum Taurat. Sebab: "Tidak ada seorang pun yang dibenarkan" karena melakukan hukum Taurat.`,
      },
      {
        order: 9,
        label: "Harus Terima Kristus",
        verse: "Roma 10:13",
        text: `Sebab, "siapa saja yang berseru kepada nama Tuhan, akan diselamatkan."`,
      },
      {
        order: 10,
        label: "Harus Terima Kristus",
        verse: "Yohanes 1:12",
        text: "Namun semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya;",
      },
      {
        order: 11,
        label: "Jaminan Keselamatan",
        verse: "Yohanes 10:27-28",
        text: "Domba-domba-Ku mendengarkan suara-Ku dan Aku mengenal mereka dan mereka mengikut Aku, dan Aku memberikan hidup yang kekal kepada mereka dan mereka pasti tidak akan binasa sampai selama-lamanya dan seorang pun tidak akan merebut mereka dari tangan-Ku.",
      },
      {
        order: 12,
        label: "Jaminan Keselamatan",
        verse: "Mazmur 125:1",
        text: "Nyanyian ziarah. Orang yang percaya kepada Tuhan adalah seperti Gunung Sion: tidak tergoyahkan dan tetap untuk selama-lamanya.",
      },
    ],
  },
];
